ollama:
  service:
    port: 80

webui:
  annotations: {}
  podAnnotations: {}
  replicaCount: 1
  image:
    repository: ghcr.io/open-webui/open-webui
    tag: ""
    pullPolicy: Always
  resources: {}
  ingress:
    enabled: false
    class: ""
    annotations: {}
    host: ""
    tls: false
    existingSecret: ""
  persistence:
    enabled: true
    size: 2Gi
    existingClaim: ""
    accessModes:
    - ReadWriteOnce
    storageClass: ""
    selector: {}
    annotations: {}
  nodeSelector: {}
  tolerations: []
  service:
    type: ClusterIP
    annotations: {}
    port: 80
    containerPort: 8080
    nodePort: ""
    labels: {}
    loadBalancerClass: ""
